def trim(phrase, size):
  if len(phrase) <= size: return phrase
  return phrase[:(size - 3)] + "..." if len(phrase[:size]) > 3 else phrase[:size] + "..."

  
  
trim("Him", 2) # Hi...
trim("He", 1) # H...
trim("Creating kata is fun", 14) # Creating ka...
trim("Coding rocks", 12) # Coding rocks
trim("QZ apxk", 3) # QZ ...
trim("pgNT", 1) # p...
trim("bfIX buW", 6) # bfI...